
# This file was *autogenerated* from the file p203.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_50 = Integer(50)
def main() :
  N = _sage_const_50 
  L = []
  for i in (ellipsis_range(_sage_const_0 ,Ellipsis,N)) :
    for j in (ellipsis_range(_sage_const_0 ,Ellipsis,floor(i/_sage_const_2 ))) :
      L = L + [binomial(i,j)]
  S = filter(is_squarefree, set(L))
  print(sum(S))

if __name__ == "__main__" :
  main()

